# Generated by Django 5.2.12 on 2026-03-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amostras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('CONCL', 'Concluida'), ('CANC', 'Cancelada')], default='PEND', max_length=5)),
                ('inicializada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('amostra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='amostras.amostras')),
            ],
        ),
    ]
