# Generated by Django 5.2.12 on 2026-03-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='imagem_analise',
            field=models.ImageField(blank=True, null=True, upload_to='analises/'),
        ),
    ]
