# Generated by Django 5.2.12 on 2026-04-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_analise_imagem_analise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='imagem_analise',
        ),
        migrations.AddField(
            model_name='analise',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='analise'),
        ),
    ]
