# Generated by Django 6.0.4 on 2026-05-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_remove_analise_imagem_analise_analise_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analise',
            old_name='amostra',
            new_name='lamina',
        ),
    ]
