# Generated by Django 6.0.4 on 2026-05-01 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_rename_amostra_analise_lamina'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='confianca',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analise',
            name='data_analise',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analise',
            name='parasita_detectado',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
