# Generated by Django 6.0.4 on 2026-05-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0004_alter_amostras_paciente_alter_amostras_tipo_do_exame'),
        ('analise', '0005_analise_confianca_analise_data_analise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='lamina',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analise', to='amostras.amostras'),
        ),
    ]
