# Generated by Django 6.0.4 on 2026-05-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0006_alter_analise_lamina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='confianca',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
