# Generated by Django 6.0.4 on 2026-05-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0007_alter_analise_confianca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='parasita_detectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
