# Generated by Django 5.2.12 on 2026-03-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_do_exame', models.CharField(choices=[('SANGUE', 'Sangue'), ('FEZES', 'Fezes'), ('OUTRO', 'Outro')], max_length=6)),
                ('imagem', models.ImageField(upload_to='uploads/')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='paciente.paciente')),
            ],
        ),
    ]
