# Generated by Django 5.2.12 on 2026-03-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0002_alter_amostras_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostras',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='amostras/'),
        ),
    ]
