# Generated by Django 5.2.12 on 2026-04-01 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0003_alter_amostras_imagem'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostras',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='amostras',
            name='tipo_do_exame',
            field=models.CharField(blank=True, choices=[('SANGUE', 'Sangue'), ('FEZES', 'Fezes'), ('OUTRO', 'Outro')], max_length=6, null=True),
        ),
    ]
