# Generated by Django 5.2.11 on 2026-03-03 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_do_exame', models.CharField(choices=[('HELMINTO', 'Helminto'), ('PROTOZOÁRIO', 'Protozoário'), ('GIARDIA', 'Giardia')], max_length=11)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
