# Generated by Django 5.2.11 on 2026-03-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=64)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
